name: "Open WebUI"
description: "Open WebUI is an extensible, self-hosted interface for AI that adapts to your workflow, all while operating entirely offline."
version: "0.6.41"
slug: "open-webui"
arch:
  - amd64
url: https://openwebui.com
map:
  - type: addon_config
    read_only: False
    path: /app/backend/data
  - type: data
    path: /root/.ollama
legacy: True
ports:
  8084/tcp: 8084
  11434/tcp: 11143

ports_description:
  8084/tcp:  Open WebUI port
  11434/tcp: Ollama port

options:
  port: 8084
  env_vars: []
schema:
  port: port
  env_vars:
    - name: match(^[A-Z0-9_]+$)
      value: str
init: false
startup: application
image: "grunjol/open-webui-{arch}"
